# SOPS Configuration File
# This file defines which keys can encrypt/decrypt secrets

# Age key recipients (YubiKeys + backup key)
keys:
  - &yubikey1 age1yubikey1qgsgw87dmznvsv05gwsrf6yvh443k6s66q8ul9ywemrxnzeksqk2xw9hu7t  # YubiKey 1
  - &yubikey2 age1yubikey1qthg8lfk3ja6uxem83309ju33py3geuk38fjza74q8fdy4snhr57qpdqc0w  # YubiKey 2
  - &yubikey3 age1yubikey1qwmfm3lglfxxysp2jshxkfqzn07gnwkg2ks7g46lnnl73py2k8j7ueq2090  # YubiKey 3
  - &backup age128yht6zyg2gl35g36uqq0am9klmumx0cukf5lnex75nm8efzpflsnnxjyz  # Backup key (password-protected)

# Creation rules define which keys can decrypt which files
creation_rules:
  # SSH keys - can be decrypted by any YubiKey or the backup key
  - path_regex: secrets/ssh/.*
    age: >-
      age1yubikey1qgsgw87dmznvsv05gwsrf6yvh443k6s66q8ul9ywemrxnzeksqk2xw9hu7t,age1yubikey1qthg8lfk3ja6uxem83309ju33py3geuk38fjza74q8fdy4snhr57qpdqc0w,age1yubikey1qwmfm3lglfxxysp2jshxkfqzn07gnwkg2ks7g46lnnl73py2k8j7ueq2090,age128yht6zyg2gl35g36uqq0am9klmumx0cukf5lnex75nm8efzpflsnnxjyz

  # Default rule for all other secrets
  - path_regex: secrets/.*
    age: >-
      age1yubikey1qgsgw87dmznvsv05gwsrf6yvh443k6s66q8ul9ywemrxnzeksqk2xw9hu7t,age1yubikey1qthg8lfk3ja6uxem83309ju33py3geuk38fjza74q8fdy4snhr57qpdqc0w,age1yubikey1qwmfm3lglfxxysp2jshxkfqzn07gnwkg2ks7g46lnnl73py2k8j7ueq2090,age128yht6zyg2gl35g36uqq0am9klmumx0cukf5lnex75nm8efzpflsnnxjyz
