[window]
startup_mode = "Fullscreen"
option_as_alt = "Both"

[terminal.shell]
program = "/opt/homebrew/bin/zellij"

[env]
XDG_CONFIG_HOME = "/Users/anthony/.config"

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
size = 15

[terminal]
