theme = "onedark"

[keys.insert.j]
k = "normal_mode" # Maps `jk` to exit insert mode
[keys.insert.k]
j = "normal_mode" # Maps `jk` to exit insert mode

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
