# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8483bed3-03f2-4bf4-8730-4b30b6fea00f";
      fsType = "ext4";
    };

  # LUKS encryption with YubiKey FIDO2 support
  # See modules/nixos/yubikey-encryption.nix for enrollment instructions
  boot.initrd.luks.devices."luks-29509493-cf8a-43ad-aafe-421a456ba58a" = {
    device = "/dev/disk/by-uuid/29509493-cf8a-43ad-aafe-421a456ba58a";

    # Enable FIDO2 (YubiKey) unlock at boot
    # Manual enrollment required: sudo systemd-cryptenroll --fido2-device=auto \
    #   --fido2-with-user-verification=true \
    #   /dev/disk/by-uuid/29509493-cf8a-43ad-aafe-421a456ba58a
    crypttabExtraOpts = [
      "fido2-device=auto"           # Automatically detect any enrolled FIDO2 token
      "token-timeout=10"            # Wait 10 seconds for token before falling back
    ];

    # Note: Password fallback is automatic with systemd stage 1
    # (fallbackToPassword option not needed - implied by systemd)
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4E47-EC78";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
