"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Anthony M. Bonafide"
email = "AnthonyMBonafide@pm.me"

[ui]
default-command = "log"

[revsets]
# Show commits that are not in `main@origin`
# log = "present(@) | ancestors(immutable_heads().., 10) | present(trunk())"

[revset-aliases]
# set all remote bookmarks (commits pushed to remote branches) to be immutable
# this has the side effect of making a new change on top of the existing one
# when pushing changes. Also, displaying with `jj log` or simply `jj`
'immutable_heads()' = "builtin_immutable_heads() | remote_bookmarks()"
